/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from './app.component';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from './friends.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from './friends.component.ngfactory';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_AppComponent:any[] = [];
var renderType_AppComponent:import0.RenderComponentType = null;
class _View_AppComponent0 extends import1.AppView<import2.AppComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  private _appEl_3:import3.AppElement;
  _FriendsComponent_3_4:import4.FriendsComponent;
  _text_4:any;
  private _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',null);
    this._text_1 = this.renderer.createText(this._el_0,'',null);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',null);
    this._el_3 = this.renderer.createElement(parentRenderNode,'friends',null);
    this._appEl_3 = new import3.AppElement(3,null,this,this._el_3);
    var compView_3:any = import9.viewFactory_FriendsComponent0(this.viewUtils,this.injector(3),this._appEl_3);
    this._FriendsComponent_3_4 = new import4.FriendsComponent();
    this._appEl_3.initComponent(this._FriendsComponent_3_4,[],compView_3);
    compView_3.create(this._FriendsComponent_3_4,[],null);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import8.uninitialized;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.FriendsComponent) && (3 === requestNodeIndex))) { return this._FriendsComponent_3_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,'\n  ',this.context.title,'\n');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import2.AppComponent> {
  if ((renderType_AppComponent === null)) { (renderType_AppComponent = viewUtils.createRenderComponentType('/Users/tor/Development/angular2-offline-compiler/src/app/app.component.html',0,import10.ViewEncapsulation.None,styles_AppComponent)); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
const styles_AppComponent_Host:any[] = [];
var renderType_AppComponent_Host:import0.RenderComponentType = null;
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import3.AppElement;
  _AppComponent_0_4:import2.AppComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-root',rootSelector,null);
    this._appEl_0 = new import3.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import2.AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === null)) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,null,styles_AppComponent_Host)); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import11.ComponentFactory<import2.AppComponent> = new import11.ComponentFactory<import2.AppComponent>('app-root',viewFactory_AppComponent_Host0,import2.AppComponent);